### PR TITLE
Fix default template path in ContainerBlockService

### PR DESCRIPTION
**Pull request by eko**
I've fixed `Resources/views/Block/block_container.html.twig` to `Resources/views/BlockAdmin/block_container.html.twig` as previous one does not exists.

### CODE REVIEW

**Comment by qsomazzi** [comment]
:+1:

**Comment by eko** [comment]
No, :-1:, I haven't upgraded unit tests, I will do it quickly ;)

**Comment by eko** [comment]
@qsomazzi Tests has been updated for this fix. However, tests was already failing before this PR.

**Comment by qsomazzi** [comment]
@eko i'm on it, will fix them first now

**Comment by qsomazzi** [comment]
https://github.com/sonata-project/SonataDashboardBundle/pull/5

**Comment by qsomazzi** [comment]
:+1: now :)

**Comment by qsomazzi** [comment]
ping @rande

**Pull request merged**
