### PR TITLE
remove map info from css files

### PR DESCRIPTION
**Pull request by stphnpt**
### Changelog

```markdown

### Fixed
- error when using assets in Assetic with yuicompressor
```

### Subject

Avoid error when using assets in Assetic with yuicompressor

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @greg0ire

**Comment by greg0ire** [comment]
No idea whether this is the right thing to do, I don't know YUICompressor. @ju1ius, can you please advise?

**Comment by stphnpt** [comment]
It's the way it is done in SonataPageBundle (same asset management process)

**Comment by greg0ire** [comment]
If I understand correctly sourcemaps are for debugging, so it make sense indeed to remove this. So a small LGTM for me. Please merge tomorrow if there is no answer from @ju1ius .

**Comment by ju1ius** [comment]
@greg0ire sourcemaps are an invaluable tool for debugging, so the usual workflow is (with gulp) is to have two separate tasks for development and release.
For example:
* `$ gulp dev` to output an unoptimized build _with_ sourcemaps, setup watches, livereload and stuff... 
* `$ gulp dist` to compile, concat, uglify, optimize all the things _without_ sourcemaps.

And of course .gitignore `*.map` or whatever the extension is.

**Comment by stphnpt** [comment]
You can make no modification to gulp.js (with sourcemaps) if sonata-dashboard.back.**min**.css only is used in Assetic config (sonata-dashboard.back.css will fail).

To keep it consistent with SonataPageBundle, it will mean modifying its gulp.js (to have with sourcemaps) and reference sonata-page.back.**min**.css in Assetic config in sonata-project/sandbox 2.4-develop

**Comment by ju1ius** [comment]
@stphnpt I think development builds and sourcemaps should not be **commited** to the repo.
@greg0ire what do you think ?

**Comment by greg0ire** [comment]
I think they should not be commited, just ignored. But I did not understand @stphnpt 's last message, so I don't understand if it can work if we simply remove them from version control. @ju1ius,  are you saying this is mergeable but we should also do more on a later PR?

**Comment by stphnpt** [comment]
> I think development builds and sourcemaps should not be commited to the repo
I agree with @ju1ius (true for both Dashboard and Page bundles)

**Comment by Soullivaneuh** [comment]
Sorry for the auto-close. This is because we decide to work on `master` only for now.

Don't worry, to continue the work, simply reopen a new PR with the same branch but against `master` this time. :+1:

**Pull request closed without merging**
