### PR TITLE
remove map info from css files

### PR DESCRIPTION
**Pull request by stphnpt**
### Changelog

```markdown

### Fixed
- error when using assets in Assetic with yuicompressor
```

### Subject

Avoid error when using assets in Assetic with yuicompressor

### CODE REVIEW

**Comment by stphnpt** [comment]
@Soullivaneuh Build step 'Publish xUnit test result report' changed build result to FAILURE
I don't understand ? what can I do ?

**Comment by greg0ire** [comment]
You can safely ignore it, we'll probably remove this check someday.

**Comment by greg0ire** [comment]
@ju1ius can you confirm this is safe to merge?

**Comment by ju1ius** [comment]
@greg0ire LGTM

**Comment by greg0ire** [comment]
Thanks @stphnpt @ju1ius

**Pull request merged**
