### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by core23**
There could be a reference to the upcomming ``AdminBundle``.

### CODE REVIEW

**Comment by qsomazzi** [comment]
@core23 can you also fix the CS here please : 

 > Starting Tests

Loaded config from "/project/.php_cs"
.......F.................................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) Admin/DashboardAdmin.php (align_double_arrow)

**Comment by Soullivaneuh** [comment]
@qsomazzi @core23 The CS is not related.

It's a bug reported in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1450

**Comment by qsomazzi** [comment]
Oh my bad, then it looks ok for me :+1:

**Comment by qsomazzi** [comment]
@Soullivaneuh can we merge this ?

**Comment by Soullivaneuh** [comment]
I think so.

**Pull request merged**
