### PR TITLE
Assets management documentation

### PR DESCRIPTION
**Pull request by stphnpt**
### Subject

Add documentation to explain how to manage assets for generating
SonataDashboardBundle css and js files (back and front).

NB:
npm WARN SonataDashboardBundle@0.0.1 No repository field.
npm WARN SonataDashboardBundle@0.0.1 No license field.

### To do

- [x] Update the documentation

### CODE REVIEW

**Comment by stphnpt** [comment]
@greg0ire BTW, on https://sonata-project.org, the documentation is not updated and the SearchBundle is labelled "Dashboard" in the left sidebar menu.

**Comment by greg0ire** [comment]
@Soullivaneuh , can you help with that ?

**Comment by Soullivaneuh** [comment]
@stphnpt @greg0ire Already fixed. Certainly a cache issue. I saw the fix online this morning at home, but not here on my work computer.

I think we just have to wait. :-)

cc @rande

**Comment by Soullivaneuh** [comment]
Defintily a cache "issue":

* https://sonata-project.org/bundles/dashboard/master/doc/index.html -> I don't see dashboard on left menu
* https://sonata-project.org/bundles/dashboard/master/doc/reference/introduction.html -> I see it
* https://sonata-project.org/bundles/admin-search/master/doc/reference/createquery.html -> The admin search menu looks good here

**Comment by stphnpt** [comment]
https://sonata-project.org/bundles/dashboard/master/doc/reference/introduction.html -> the admin search is labelled "Dashboard"

**Comment by rande** [comment]
Cache: https://sonata-project.org/bundles/dashboard/master/doc/reference/introduction.html?qsd

**Comment by Soullivaneuh** [comment]
@stphnpt Pleas re-read my comments. :-)

**Pull request merged**
